XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    BBBB BBBBBB
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBXX
XXXXXXX
XXXXXX
XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXX
                XXXXX
XXXX                XXX XXXXXXXXXXXXXXXXXXXX
XXXX                    XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
XXXX                XXXXXXXX
XXXX                XXX XXXXXXXXXXXXXXXXXXXX
XXXX                    XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
XXXX                XXXXXXXX
XXXX                XXX XXXXXXXXXXXXXXXXXXXX
XXXX                    XX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXX                XXXXXXXX
            XXXXX
            XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                BBBBBBBBBB
                XXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBB BBBBBBB
XXXX     XXXXXXX   XXX
BBBBBBBB
XXXXXXX
XXXXXXX