BBBBBBB BBBBBBBBBBB
BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXX
        BBB BBBBBBBBBB BB BBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXX
                XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                        BBBBBBBBBB
                        XXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX
                        XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX
                    XXXXX XXXXXXXXBBB BBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                        BBBBBBBBBB
                        XXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX
                        XXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
                            XXXX
                        XXXXXXXXX
                    XXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
                    XXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXX
                    XXX XXXXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
                        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBBBB BBBBBBBBBBBBBBBBBBXXXXX
                    XXXXX
                    XXXX                XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
        BBBBBB
    XXXXXX
XXXXXX
BBBBBBBB
