BBBBBBB BBBBBBBBBBB
BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXX
                BBBBBBBBBB
                
                XXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX
                XXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX
            XXXXXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB